<?php
/**
 * ProgressDataTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Yoast\MyYoastApiClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * MyYoast server
 *
 * The MyYoast server NestJS Api
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.15
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Yoast\MyYoastApiClient;

/**
 * ProgressDataTest Class Doc Comment
 *
 * @category    Class
 * @description ProgressData
 * @package     Yoast\MyYoastApiClient
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ProgressDataTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ProgressData"
     */
    public function testProgressData()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "progress"
     */
    public function testPropertyProgress()
    {
    }

    /**
     * Test attribute "outsideTrialProgress"
     */
    public function testPropertyOutsideTrialProgress()
    {
    }

    /**
     * Test attribute "studentId"
     */
    public function testPropertyStudentId()
    {
    }

    /**
     * Test attribute "courseId"
     */
    public function testPropertyCourseId()
    {
    }

    /**
     * Test attribute "isTrial"
     */
    public function testPropertyIsTrial()
    {
    }

    /**
     * Test attribute "trialCompleted"
     */
    public function testPropertyTrialCompleted()
    {
    }
}
