<?php
/**
 * SubscriptionTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Yoast\MyYoastApiClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * MyYoast
 *
 * The MyYoast Api
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.66
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Yoast\MyYoastApiClient;

use PHPUnit\Framework\TestCase;

/**
 * SubscriptionTest Class Doc Comment
 *
 * @category    Class
 * @description Subscription
 * @package     Yoast\MyYoastApiClient
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SubscriptionTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "Subscription"
     */
    public function testSubscription()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "startDate"
     */
    public function testPropertyStartDate()
    {
    }

    /**
     * Test attribute "endDate"
     */
    public function testPropertyEndDate()
    {
    }

    /**
     * Test attribute "sourceId"
     */
    public function testPropertySourceId()
    {
    }

    /**
     * Test attribute "sourceLineItemId"
     */
    public function testPropertySourceLineItemId()
    {
    }

    /**
     * Test attribute "sourceShopId"
     */
    public function testPropertySourceShopId()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "currency"
     */
    public function testPropertyCurrency()
    {
    }

    /**
     * Test attribute "date"
     */
    public function testPropertyDate()
    {
    }

    /**
     * Test attribute "price"
     */
    public function testPropertyPrice()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "nextPayment"
     */
    public function testPropertyNextPayment()
    {
    }

    /**
     * Test attribute "limit"
     */
    public function testPropertyLimit()
    {
    }

    /**
     * Test attribute "used"
     */
    public function testPropertyUsed()
    {
    }

    /**
     * Test attribute "createdAt"
     */
    public function testPropertyCreatedAt()
    {
    }

    /**
     * Test attribute "modifiedAt"
     */
    public function testPropertyModifiedAt()
    {
    }

    /**
     * Test attribute "requiresManualRenewal"
     */
    public function testPropertyRequiresManualRenewal()
    {
    }

    /**
     * Test attribute "renewalSecret"
     */
    public function testPropertyRenewalSecret()
    {
    }

    /**
     * Test attribute "subscriptionNumber"
     */
    public function testPropertySubscriptionNumber()
    {
    }

    /**
     * Test attribute "lastBillingTerm"
     */
    public function testPropertyLastBillingTerm()
    {
    }

    /**
     * Test attribute "subscriberId"
     */
    public function testPropertySubscriberId()
    {
    }

    /**
     * Test attribute "productId"
     */
    public function testPropertyProductId()
    {
    }

    /**
     * Test attribute "provisionerId"
     */
    public function testPropertyProvisionerId()
    {
    }
}
