<?php
/**
 * UpdateUserDtoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Yoast\MyYoastApiClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * MyYoast
 *
 * The MyYoast Api
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.68
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Yoast\MyYoastApiClient;

use PHPUnit\Framework\TestCase;

/**
 * UpdateUserDtoTest Class Doc Comment
 *
 * @category    Class
 * @description UpdateUserDto
 * @package     Yoast\MyYoastApiClient
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class UpdateUserDtoTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "UpdateUserDto"
     */
    public function testUpdateUserDto()
    {
    }

    /**
     * Test attribute "userEmail"
     */
    public function testPropertyUserEmail()
    {
    }

    /**
     * Test attribute "userFirstName"
     */
    public function testPropertyUserFirstName()
    {
    }

    /**
     * Test attribute "userLastName"
     */
    public function testPropertyUserLastName()
    {
    }

    /**
     * Test attribute "enabled"
     */
    public function testPropertyEnabled()
    {
    }
}
