<?php
/**
 * DefaultApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Yoast\MyYoastApiClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * MyYoast
 *
 * The MyYoast Api
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.36
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Yoast\MyYoastApiClient;

use Yoast\MyYoastApiClient\Configuration;
use Yoast\MyYoastApiClient\ApiException;
use Yoast\MyYoastApiClient\ObjectSerializer;

/**
 * DefaultApiTest Class Doc Comment
 *
 * @category Class
 * @package  Yoast\MyYoastApiClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DefaultApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for addAgency
     *
     * .
     *
     */
    public function testAddAgency()
    {
    }

    /**
     * Test case for addOwnerToAgency
     *
     * .
     *
     */
    public function testAddOwnerToAgency()
    {
    }

    /**
     * Test case for createClient
     *
     * .
     *
     */
    public function testCreateClient()
    {
    }

    /**
     * Test case for createReview
     *
     * .
     *
     */
    public function testCreateReview()
    {
    }

    /**
     * Test case for disconnectOwnerFromAgency
     *
     * .
     *
     */
    public function testDisconnectOwnerFromAgency()
    {
    }

    /**
     * Test case for getAllAgenciesWithUsers
     *
     * .
     *
     */
    public function testGetAllAgenciesWithUsers()
    {
    }

    /**
     * Test case for getAllForAgency
     *
     * .
     *
     */
    public function testGetAllForAgency()
    {
    }

    /**
     * Test case for getAllForCustomer
     *
     * .
     *
     */
    public function testGetAllForCustomer()
    {
    }

    /**
     * Test case for getAllReviews
     *
     * .
     *
     */
    public function testGetAllReviews()
    {
    }

    /**
     * Test case for getById
     *
     * .
     *
     */
    public function testGetById()
    {
    }

    /**
     * Test case for getClientById
     *
     * .
     *
     */
    public function testGetClientById()
    {
    }

    /**
     * Test case for setTOTPTwoFactorConfig
     *
     * .
     *
     */
    public function testSetTOTPTwoFactorConfig()
    {
    }

    /**
     * Test case for updateClientById
     *
     * .
     *
     */
    public function testUpdateClientById()
    {
    }

    /**
     * Test case for updateClientById_0
     *
     * .
     *
     */
    public function testUpdateClientById0()
    {
    }
}
