<?php
/**
 * MailingListApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Yoast\MyYoastApiClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * MyYoast
 *
 * The MyYoast Api
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.36
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Yoast\MyYoastApiClient;

use Yoast\MyYoastApiClient\Configuration;
use Yoast\MyYoastApiClient\ApiException;
use Yoast\MyYoastApiClient\ObjectSerializer;

/**
 * MailingListApiTest Class Doc Comment
 *
 * @category Class
 * @package  Yoast\MyYoastApiClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class MailingListApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for checkGetRoute
     *
     * .
     *
     */
    public function testCheckGetRoute()
    {
    }

    /**
     * Test case for getStatus
     *
     * Get the subscription status..
     *
     */
    public function testGetStatus()
    {
    }

    /**
     * Test case for isSubscribedToNewsletter
     *
     * Get the subscription status..
     *
     */
    public function testIsSubscribedToNewsletter()
    {
    }

    /**
     * Test case for mailChimpWebhook
     *
     * Entry point for the mailchimp webhooks.
     *
     */
    public function testMailChimpWebhook()
    {
    }

    /**
     * Test case for mailblueWebhook
     *
     * Entry point for the mailblue webhooks.
     *
     */
    public function testMailblueWebhook()
    {
    }

    /**
     * Test case for removeContactCustomField
     *
     * Delete contact tags and/or fields..
     *
     */
    public function testRemoveContactCustomField()
    {
    }

    /**
     * Test case for setContactCustomField
     *
     * Update contact tags and/or fields..
     *
     */
    public function testSetContactCustomField()
    {
    }

    /**
     * Test case for setContactTag
     *
     * Update contact tags and/or fields..
     *
     */
    public function testSetContactTag()
    {
    }

    /**
     * Test case for subscribe
     *
     * Subscribe contact to a mailing list..
     *
     */
    public function testSubscribe()
    {
    }

    /**
     * Test case for subscribeToNewsletter
     *
     * Subscribe contact to the newsletter..
     *
     */
    public function testSubscribeToNewsletter()
    {
    }

    /**
     * Test case for unsubscribe
     *
     * Unsubscribe to a mailing list..
     *
     */
    public function testUnsubscribe()
    {
    }

    /**
     * Test case for unsubscribeFromNewsletter
     *
     * Unsubscribe to a mailing list..
     *
     */
    public function testUnsubscribeFromNewsletter()
    {
    }
}
