<?php
/**
 * PackagesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Yoast\MyYoastApiClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * MyYoast
 *
 * The MyYoast Api
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.68
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Yoast\MyYoastApiClient;

use Yoast\MyYoastApiClient\Configuration;
use Yoast\MyYoastApiClient\ApiException;
use Yoast\MyYoastApiClient\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * PackagesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Yoast\MyYoastApiClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PackagesApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for serveArchiveZIP
     *
     * Serves an .zip of the plugin..
     *
     */
    public function testServeArchiveZIP()
    {
    }

    /**
     * Test case for servePackagesJSON
     *
     * Serves the general packages.json file..
     *
     */
    public function testServePackagesJSON()
    {
    }

    /**
     * Test case for serveProvider2JSON
     *
     * Serves the requested provider.json.
     *
     */
    public function testServeProvider2JSON()
    {
    }

    /**
     * Test case for serveProviderJSON
     *
     * Serves the requested provider.json.
     *
     */
    public function testServeProviderJSON()
    {
    }
}
