<?php
/**
 * SiteApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Yoast\MyYoastApiClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * MyYoast server
 *
 * The MyYoast server NestJS Api
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.10
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Yoast\MyYoastApiClient;

use Yoast\MyYoastApiClient\Configuration;
use Yoast\MyYoastApiClient\ApiException;
use Yoast\MyYoastApiClient\ObjectSerializer;

/**
 * SiteApiTest Class Doc Comment
 *
 * @category Class
 * @package  Yoast\MyYoastApiClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SiteApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for apiSitesBulkPost
     *
     * Create many Site.
     *
     */
    public function testApiSitesBulkPost()
    {
    }

    /**
     * Test case for apiSitesCurrentGet
     *
     * Get the current connected site for an access token..
     *
     */
    public function testApiSitesCurrentGet()
    {
    }

    /**
     * Test case for apiSitesGet
     *
     * Retrieve many Site.
     *
     */
    public function testApiSitesGet()
    {
    }

    /**
     * Test case for apiSitesIdDelete
     *
     * Delete one Site.
     *
     */
    public function testApiSitesIdDelete()
    {
    }

    /**
     * Test case for apiSitesIdGet
     *
     * Retrieve one Site.
     *
     */
    public function testApiSitesIdGet()
    {
    }

    /**
     * Test case for apiSitesIdPatch
     *
     * Update one Site.
     *
     */
    public function testApiSitesIdPatch()
    {
    }

    /**
     * Test case for apiSitesIndexPost
     *
     * .
     *
     */
    public function testApiSitesIndexPost()
    {
    }

    /**
     * Test case for apiSitesPost
     *
     * Create one Site.
     *
     */
    public function testApiSitesPost()
    {
    }

    /**
     * Test case for apiSitesSwitchSubscriptionNumberOfTimesPost
     *
     * Switches the subscription for a number of times..
     *
     */
    public function testApiSitesSwitchSubscriptionNumberOfTimesPost()
    {
    }

    /**
     * Test case for apiSitesSwitchSubscriptionPost
     *
     * Switches the subscription for a number of times..
     *
     */
    public function testApiSitesSwitchSubscriptionPost()
    {
    }

    /**
     * Test case for apiSitesTransferPost
     *
     * Transfer sites..
     *
     */
    public function testApiSitesTransferPost()
    {
    }
}
