<?php
/**
 * SubscriptionApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Yoast\MyYoastApiClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * MyYoast server
 *
 * The MyYoast server NestJS Api
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.36
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Yoast\MyYoastApiClient;

use Yoast\MyYoastApiClient\Configuration;
use Yoast\MyYoastApiClient\ApiException;
use Yoast\MyYoastApiClient\ObjectSerializer;

/**
 * SubscriptionApiTest Class Doc Comment
 *
 * @category Class
 * @package  Yoast\MyYoastApiClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SubscriptionApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for subscriptionControllerCalculateExpansionPrice
     *
     * Calculate expansion price.
     *
     */
    public function testSubscriptionControllerCalculateExpansionPrice()
    {
    }

    /**
     * Test case for subscriptionControllerDeleteOne
     *
     * Delete a subscription.
     *
     */
    public function testSubscriptionControllerDeleteOne()
    {
    }

    /**
     * Test case for subscriptionControllerForceCancel
     *
     * Forcefully cancel a subscription.
     *
     */
    public function testSubscriptionControllerForceCancel()
    {
    }

    /**
     * Test case for subscriptionControllerGetExpiringSubscriptions
     *
     * .
     *
     */
    public function testSubscriptionControllerGetExpiringSubscriptions()
    {
    }

    /**
     * Test case for subscriptionControllerGetMany
     *
     * Get subscriptions.
     *
     */
    public function testSubscriptionControllerGetMany()
    {
    }

    /**
     * Test case for subscriptionControllerGetManyPaged
     *
     * Get subscriptions.
     *
     */
    public function testSubscriptionControllerGetManyPaged()
    {
    }

    /**
     * Test case for subscriptionControllerGetOne
     *
     * Get a subscription.
     *
     */
    public function testSubscriptionControllerGetOne()
    {
    }

    /**
     * Test case for subscriptionControllerLinkSite
     *
     * Link a subscription to provided site URL.
     *
     */
    public function testSubscriptionControllerLinkSite()
    {
    }

    /**
     * Test case for subscriptionControllerRecalculateSubscriptionCount
     *
     * Recalculate SubscriptionCount..
     *
     */
    public function testSubscriptionControllerRecalculateSubscriptionCount()
    {
    }

    /**
     * Test case for subscriptionControllerRenew
     *
     * Renew subscriptions.
     *
     */
    public function testSubscriptionControllerRenew()
    {
    }

    /**
     * Test case for subscriptionControllerSetExpiryDate
     *
     * Set Date..
     *
     */
    public function testSubscriptionControllerSetExpiryDate()
    {
    }

    /**
     * Test case for subscriptionControllerSwitchPaymentMethod
     *
     * .
     *
     */
    public function testSubscriptionControllerSwitchPaymentMethod()
    {
    }

    /**
     * Test case for subscriptionControllerTransferOwnership
     *
     * Transfer subscription ownership.
     *
     */
    public function testSubscriptionControllerTransferOwnership()
    {
    }

    /**
     * Test case for subscriptionControllerUpgrade
     *
     * Upgrade subscriptions.
     *
     */
    public function testSubscriptionControllerUpgrade()
    {
    }
}
