<?php
/**
 * SubscriptionApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Yoast\MyYoastApiClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * MyYoast server
 *
 * The MyYoast server NestJS Api
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.10
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Yoast\MyYoastApiClient;

use Yoast\MyYoastApiClient\Configuration;
use Yoast\MyYoastApiClient\ApiException;
use Yoast\MyYoastApiClient\ObjectSerializer;

/**
 * SubscriptionApiTest Class Doc Comment
 *
 * @category Class
 * @package  Yoast\MyYoastApiClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SubscriptionApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for apiSubscriptionsBulkPost
     *
     * Create many Subscription.
     *
     */
    public function testApiSubscriptionsBulkPost()
    {
    }

    /**
     * Test case for apiSubscriptionsExpiringGet
     *
     * .
     *
     */
    public function testApiSubscriptionsExpiringGet()
    {
    }

    /**
     * Test case for apiSubscriptionsGet
     *
     * Retrieve many Subscription.
     *
     */
    public function testApiSubscriptionsGet()
    {
    }

    /**
     * Test case for apiSubscriptionsIdDelete
     *
     * Delete one Subscription.
     *
     */
    public function testApiSubscriptionsIdDelete()
    {
    }

    /**
     * Test case for apiSubscriptionsIdGet
     *
     * Retrieve one Subscription.
     *
     */
    public function testApiSubscriptionsIdGet()
    {
    }

    /**
     * Test case for apiSubscriptionsIdPatch
     *
     * Update one Subscription.
     *
     */
    public function testApiSubscriptionsIdPatch()
    {
    }

    /**
     * Test case for apiSubscriptionsIdRecalculateSubscriptionCountPost
     *
     * Recalculate SubscriptionCount..
     *
     */
    public function testApiSubscriptionsIdRecalculateSubscriptionCountPost()
    {
    }

    /**
     * Test case for apiSubscriptionsPost
     *
     * Create one Subscription.
     *
     */
    public function testApiSubscriptionsPost()
    {
    }
}
